### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by joaomcteixeira** [martin3141/spant#9]
Hi @martin3141 , I am a reviewer at https://github.com/openjournals/joss-reviews/issues/3646

I am running Ubuntu 20.04 and tried to install R and `spant` following the instructions in the repository. 
 
* installed R with, `sudo apt install r-base`, everything went okay :+1:
* installed R-studio downloading from https://www.rstudio.com/products/rstudio/download/#download (`.deb`), also okay :+1:
* on R-studio I ran `install.packages("spant", dependencies = TRUE)`

it took about 40 minutes to finish the installation and ended with:

```
Warning in install.packages :
  installation of package ‘spant’ had non-zero exit status
```

I closed and reopened R-studio and did and got:

```R
library(spant)
Error in library(spant) : there is no package called ‘spant’
```

Am I doing something wrong?
thanks

**Comment by martin3141** [comment]
Hi @joaomcteixeira,

Thanks for taking the time to review this package!

So R compiles packages from source by default on Linux, and yes this can unfortunately time a long time. For Windows and Mac things are much faster because pre-compiled binaries are made available on CRAN.

Your failure was very likely to be a missing system library that one of spant dependencies needs to compile. The missing library will be listed somewhere above the error message, however these messages can be hard to spot.

I just tried installing on a semi-fresh Ubuntu 20.04 install via WSL and needed to install the following:

`sudo apt install libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev`

Hopefully the above will solve your problem.

Martin

**Comment by joaomcteixeira** [comment]
Hi,

But was an Ubuntu installation or a "ubuntu on windows" kind-of installation?

I installed R with anaconda, and inside anaconda-R I run `install.packages("spant", dependencies = TRUE)`, and still the same issue, a forever installation. A possible solution would be to list the dependencies in a anaconda requirement file. What are exactly all the dependencies `spant` needs from CRAN? It is rare if those are not in Anaconda. We can try to build that together.

**Comment by martin3141** [comment]
Something else to try is : `install.packages("spant")` as this will not install some of the less important dependencies.

**Comment by joaomcteixeira** [comment]
Hi @martin3141 

I could install `spant` by installing the libraries manually with anaconda. It works very nice as expected when using conda. This is what I did:

1. just in case, I installed what you told me on the global scope: `sudo apt install libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev`
2. created a new Anaconda env for R following these instructions [link](https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/#creating-an-environment-with-r)
3. I installed the minimum required packaged for `spant`, which are:

```bash
conda activate r_env
conda install -c r r-nloptr
conda install -c conda-forge r-rniftyreg
conda install -c conda-forge r-ptw
```

I execute a couple of your examples in the Jupyter Notebook and they work great.

Then, I tried to create an Anaconda environment considering all `spant` dependencies, here's the result:

```yml
name: spant
channels:
    - conda-forge
    - r
dependencies:
    - r-base
    - r-essentials
    - r-abind
    - r-plyr
    - r-foreach
    - r-pracma
    - r-stringr
    - r-signal
    - r-matrixcalc
    - r-minpack.lm
    - r-nnls
    - r-r.utils
    - r-graphicsqc
    - r-expm
    - r-smoother
    - r-readr
    - r-magrittr
    - r-ptw
    - r-mmand
    - r-RNifti
    - r-RNiftyReg
    - r-fields
    - r-MASS
    - r-numDeriv
    - r-nloptr
    - r-irlba
    - r-tibble
    - r-jsonlite
    - r-viridisLite
    - r-shiny
    - r-miniUI
    - r-knitr
    - r-rmarkdown
    - r-testthat
    - r-ragg
    - r-doParallel
    #- r-complexplus
    #- r-grDevices
```

I could not find on Anaconda repositories the `complexplus` package. The `grDevices` can be replaced by [farver](https://github.com/thomasp85/farver), I think. But I believe that would require you to change the `spant` code in some parts.

Anyway, with the configuration above, even without these two packages, the Anaconda environment builds easily, and after, the command:

```r
install.packages("spant")
```

works very nice also.

These anaconda instructions would work for Win, Mac, and Linux alike (in principle).

The final instructions would be (after installing Anaconda):

```
conda env create -f spant_requirements.yml
conda activate spant
```

Where `spant_requirements.yml` is a file with the contents of the dependencies as I pasted above. You can change the name of the environment; here I named it `spant` for simplicity. It is up to the user to install RStudio (also available in Anaconda).

I think you can add these instructions to your package. They would help you a lot getting new users.

Cheers,
